# Generated by Django 5.0.2 on 2024-05-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="data_creeated",
            new_name="data_created",
        ),
        migrations.RenameField(
            model_name="subscribe",
            old_name="data_creeated",
            new_name="data_created",
        ),
    ]
