# Generated by Django 5.0.2 on 2024-03-06 09:59

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ("shopmax", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Size name"),
        ),
        

    ]
    
