# Generated by Django 5.0.2 on 2024-03-07 10:24

from django.db import migrations, models

def set_images_size(apps, _):
    Image = apps.get_model('shopmax', 'Image')
    for i, image in enumerate(Image.objects.all(), start=1):
        image.size = image.image.size
        image.save(update_fields=('size',))
        print(i, '[IMAGE SAVED]', image.size)

class Migration(migrations.Migration):

    dependencies = [
        ("shopmax", "0003_remove_image_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            code=set_images_size,
            reverse_code=migrations.RunPython.noop
        )
    ]
